apiVersion: v1
kind: Secret
metadata:
  name: rathena-server-pwd
  labels:
    app: rathena
type: Opaque
stringData:
  mysql-pwd: oiDzEqNerL7HeA3fU # p4ss@w0rd in base64
  intersrv-passwd: p1 # p4ss@w0rd in base64
---
## https://github.com/kubernetes/contrib/tree/master/for-demos/proxy-to-service
#apiVersion: v1
#kind: Pod
#metadata:
#  name: rathena-proxy
#  labels:
#    app: rathena
#    version: v1.0
#    component: proxy
#spec:
#  hostname: rathena-proxy
#  containers:
#  - name: login-proxy-tcp
#    image: k8s.gcr.io/proxy-to-service:v2
#    args: [ "tcp", "6900", "rathena-server" ]
#    ports:
#    - name: login
#      protocol: TCP
#      containerPort: 6900
#      hostPort: 6900
#  - name: char-proxy-tcp
#    image: k8s.gcr.io/proxy-to-service:v2
#    args: [ "tcp", "6121", "rathena-server" ]
#    ports:
#    - name: char
#      protocol: TCP
#      containerPort: 6121
#      hostPort: 6121
#  - name: map-proxy-tcp
#    image: k8s.gcr.io/proxy-to-service:v2
#    args: [ "tcp", "5121", "rathena-server" ]
#    ports:
#    - name: map
#      protocol: TCP
#      containerPort: 5121
#      hostPort: 5121
---
# Debug machine
apiVersion: v1
kind: Pod
metadata:
  name: rathena-debug
  labels:
    app: rathena
    version: v1.0
    component: debug
spec:
  hostname: rathena-debug
  containers:
  - name: rathena-debug
    image: alpine:latest
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
---
apiVersion: v1
kind: Service
metadata:
  name: rathena-server
  labels:
    app: rathena
spec:
  ports:
    - name: login
      protocol: TCP
      port: 6900
    - name: map
      protocol: TCP
      port: 5121
    - name: char
      protocol: TCP
      port: 6121
  selector:
    app: rathena
    component: server
    version: v1.0
  #clusterIP: 10.96.254.10 # Default range: 10.96.0.0/12
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2, before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: rathena-server
  labels:
    app: rathena
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rathena
      component: server
      version: v1.0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rathena
        component: server
        version: v1.0
    spec:
      containers:
      #- image: cmilanf/rathena:latest
      - image: ghcr.io/lenaxia/docker-rathena/rathena-packetver20200401:renewal-20240805
        name: rathena-server
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rathena-server-pwd
              key: mysql-pwd
        - name: SET_INTERSRV_PASSWD
          valueFrom:
            secretKeyRef:
              name: rathena-server-pwd
              key: intersrv-passwd
        - name: MYSQL_HOST
          value: "192.168.5.15"
        - name: MYSQL_USERNAME
          value: "ragnarok"
        - name: MYSQL_DATABASE
          value: "rathena_renewal"
        - name: SET_SERVER_NAME
          value: "rAthena"
        - name: SET_INTERSRV_USERID
          value: "s1"
        - name: MYSQL_DROP_DB
          value: "0"
        - name: SET_PINCODE_ENABLED
          value: "no"
        - name: SET_START_POINT
          value: "prontera,155,182"
        - name: ADD_SUBNET_MAP1
          value: "255.255.255.255:10.96.255.255"
        - name: SET_CHAR_PUBLIC_IP
          value: "192.168.5.105"
        - name: SET_MAP_PUBLIC_IP
          value: "192.168.5.105"
        - name: MYSQL_ACCOUNTSANDCHARS
          value: "1"
            #        ports:
            #        - containerPort: 6900
            #          name: login-server
            #        - containerPort: 5121
            #          name: map-server
            #        - containerPort: 6121
            #          name: char-server
